/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.5. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input  clk // clock
    , input  rst // reset
    , input  en // enable
    , input  eta_0
    , input  eta_1
    , input  eta_2
    , input  eta_3
    , input  eta_4

      // Outputs
    , output wire  result_0
    , output wire  result_1
    , output wire  result_2
    , output wire  result_3
    );
  // ../clique3.hs:19:1-17
  wire [3:0] inputBits;
  // ../clique3.hs:19:1-17
  wire  c$ds_app_arg;
  wire [4:0] eta;
  wire [3:0] result;

  assign eta = {eta_0,   eta_1,   eta_2,
                eta_3,   eta_4};

  assign inputBits = eta[5-1 : 1];

  // map begin
  genvar i;
  generate
  for (i=0; i < 4; i = i + 1) begin : map
    wire  map_in;
    assign map_in = inputBits[i*1+:1];
    wire  map_out;
    assign map_out = map_in & ((eta[1-1:0]) & c$ds_app_arg);


    assign result[i*1+:1] = map_out;
  end
  endgenerate
  // map end

  wire [3:0] vec;
  wire  acc_2_0;
  wire  acc_1;
  wire  acc_2;
  wire  acc_3;
  wire  acc_4;
  wire  acc_1_0;
  wire  acc_1_1;
  assign c$ds_app_arg = acc_2_0;

  assign vec = inputBits;

  assign acc_1 = vec[3:3];

  assign acc_2 = vec[2:2];

  assign acc_3 = vec[1:1];

  assign acc_4 = vec[0:0];

  assign acc_1_0 = acc_1 ^ acc_2;



  assign acc_1_1 = acc_3 ^ acc_4;



  assign acc_2_0 = acc_1_0 ^ acc_1_1;





  assign result_0 = result[3:3];

  assign result_1 = result[2:2];

  assign result_2 = result[1:1];

  assign result_3 = result[0:0];


endmodule

