/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.5. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input  clk // clock
    , input  rst // reset
    , input  en // enable
    , input  eta_0
    , input  eta_1
    , input  eta_2
    , input  eta_3
    , input  eta_4

      // Outputs
    , output wire  result_0
    , output wire  result_1
    , output wire  result_2
    , output wire  result_3
    , output wire  result_4
    );
  // ../clique1.hs:11:1-14
  wire  p;
  // ../clique1.hs:11:1-14
  wire  q;
  // ../clique1.hs:11:1-14
  wire  r;
  // ../clique1.hs:11:1-14
  wire  s;
  // ../clique1.hs:11:1-14
  wire  t;
  // ../clique1.hs:11:1-14
  wire  xorResult;
  // ../clique1.hs:11:1-14
  wire  common;
  wire [4:0] eta;
  wire [4:0] result;

  assign eta = {eta_0,   eta_1,   eta_2,
                eta_3,   eta_4};

  assign p = eta[4:4];

  assign q = eta[3:3];

  assign r = eta[2:2];

  assign s = eta[1:1];

  assign t = eta[0:0];

  assign xorResult = ((p ^ q) ^ r) ^ s;

  assign common = t & xorResult;

  assign result = {common & p,   common & q,
                   common & r,   common & s,   t & (~ xorResult)};

  assign result_0 = result[4:4];

  assign result_1 = result[3:3];

  assign result_2 = result[2:2];

  assign result_3 = result[1:1];

  assign result_4 = result[0:0];


endmodule

