/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.5. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input  clk // clock
    , input  rst // reset
    , input  en // enable
    , input  eta_0
    , input  eta_1
    , input  eta_2
    , input  eta_3
    , input  eta_4

      // Outputs
    , output wire  result_0
    , output wire  result_1
    , output wire  result_2
    , output wire  result_3
    );
  // ../clique2.hs:11:1-15
  wire  common;
  // ../clique2.hs:11:1-15
  wire  t;
  // ../clique2.hs:11:1-15
  wire  c$common_app_arg;
  // ../clique2.hs:11:1-15
  wire  p;
  // ../clique2.hs:11:1-15
  wire  c$common_case_alt;
  // ../clique2.hs:11:1-15
  wire  c$common_case_alt_0;
  // ../clique2.hs:11:1-15
  wire  q;
  // ../clique2.hs:11:1-15
  wire  c$common_case_alt_1;
  // ../clique2.hs:11:1-15
  wire  c$common_case_alt_2;
  // ../clique2.hs:11:1-15
  wire  r;
  // ../clique2.hs:11:1-15
  wire  c$common_case_alt_3;
  // ../clique2.hs:11:1-15
  wire  s;
  wire [4:0] eta;
  wire [3:0] result;

  assign eta = {eta_0,   eta_1,   eta_2,
                eta_3,   eta_4};

  assign result = {common & p,   common & q,
                   common & r,   common & s};

  assign common = t & c$common_app_arg;

  assign t = eta[0:0];

  assign c$common_app_arg = p ? c$common_case_alt : c$common_case_alt_0;

  assign p = eta[4:4];

  assign c$common_case_alt = q ? c$common_case_alt_2 : c$common_case_alt_1;

  assign c$common_case_alt_0 = q ? c$common_case_alt_1 : c$common_case_alt_2;

  assign q = eta[3:3];

  assign c$common_case_alt_1 = r ? s : c$common_case_alt_3;

  assign c$common_case_alt_2 = r ? c$common_case_alt_3 : s;

  assign r = eta[2:2];

  assign c$common_case_alt_3 = s ? 1'b0 : 1'b1;

  assign s = eta[1:1];

  assign result_0 = result[3:3];

  assign result_1 = result[2:2];

  assign result_2 = result[1:1];

  assign result_3 = result[0:0];


endmodule

